services:
  sub-proxy:
    build: .
    container_name: sub-proxy
    ports:
      - "8080:80"
      - "1935:1935"
    volumes:
      - ./models:/app/models
    environment:
      - WHISPER_MODEL_PATH=/app/models/ggml-large-v3-turbo.bin
    restart: unless-stopped
