services:
  sub-proxy:
    build: .
    container_name: sub-proxy
    ports:
      - "8080:80"
      - "1935:1935"
      - "8000:8000"  # WhisperLiveKit port
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    restart: unless-stopped
