version: '3.8'

services:
  sub-proxy:
    build: .
    container_name: sub-proxy
    ports:
      - "8080:80"
      - "1935:1935"
    volumes:
      - ./models:/app/models
    environment:
      - WHISPER_CACHE_DIR=/app/models
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
