services:
  sub-proxy:
    build: .
    container_name: sub-proxy
    ports:
      - "8080:80"
      - "1935:1935"
      - "8000:8000"  # WhisperLiveKit port
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HUGGINGFACE_TOKEN=TOKEN
      - YOUTUBE_CID=
    volumes:
      - ./cache:/root/.cache/
    runtime: nvidia
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
