services:
  sub-proxy:
    build: .
    container_name: sub-proxy
    ports:
      - "8080:80"
      - "1935:1935"
      - "8000:8000"  # WhisperLiveKit port
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HUGGINGFACE_TOKEN=TOKEN
      - YOUTUBE_CID=
    volumes:
      - ./models:/root/.cache/whisper
      - ./transformers:/root/.cache/huggingface
    runtime: nvidia
    restart: unless-stopped
